Linear system solver: Matrix Struct Reference
Matrix Struct Reference
#include <matrix.hpp>
Public Member Functions
size_t index (const int &x, const int &y) const
Matrix (const int &width, const int &height, const bool &augmented)
virtual ~Matrix ()
Matrix (const Matrix &rhs)
Matrix (Matrix &&rhs) noexcept
Matrix & operator= (const Matrix &rhs)
Matrix & operator= (Matrix &&rhs) noexcept
void swap (Matrix &rhs)
double get_field (const int &x, const int &y) const
void set_field (const int &x, const int &y, double value)
std::vector< double > get_row (const int &y) const
void set_row (const int &y, std::vector< double > values)
std::vector< double > get_column (const int &x) const
void set_column (const int &x, std::vector< double > values)
bool is_square () const
Matrix get_matrix_A () const
Matrix get_transposition () const
template<typename T >
void foreach_field (T &&lambda)
Data Fields
int width
int height
double * data {}
bool augmented
Detailed Description
Struct representing matrix.
If augmented is set to true, than the matrix represents system of linear equations.
Definition at line 18 of file matrix.hpp.
Constructor & Destructor Documentation
Matrix() [1/3]
Matrix::Matrix (const int & width, const int & height, const bool & augmented)
Matrix constructor.
Parameters
width number of vectors in the matrix
height dimension of vectors in the matrix
augmented true if the matrix is augmented (last column is vector b), false otherwise
~Matrix()
virtual Matrix::~Matrix () virtual
Matrix destructor.
Matrix() [2/3]
Matrix::Matrix (const Matrix & rhs)
Copy constructor.
Parameters
rhs matrix to copy from
Matrix() [3/3]
Matrix::Matrix (Matrix && rhs) noexcept
Move constructor.
Parameters
rhs matrix to move from
Member Function Documentation
foreach_field()
template<typename T > void Matrix::foreach_field (T && lambda) inline
Executes modifying lambda function for each field of the matrix.
Template Parameters
T
Parameters
lambda function
Definition at line 153 of file matrix.hpp.
{
         for (int y = 0; y < height; ++y) {
             for (int x = 0; x < width; ++x) {
                 set_field(x, y, lambda(x, y, get_field(x, y)));
             }
         }
     };
References get_field(), height, set_field(), and width.
get_column()
std::vector<double> Matrix::get_column (const int & x) const
Parameters
x index of the column to be returned (zero based)
Returns
x-th column of the matrix as vector of elements
get_field()
double Matrix::get_field (const int & x, const int & y) const
Parameters
x index of the column in which the field is (zero based)
y index of the row in which the field is (zero based)
Returns
element on [x,y] coords in the matrix
Referenced by foreach_field().
get_matrix_A()
Matrix Matrix::get_matrix_A () const
Copies the matrix and removes the vector b from the copy. The modified copy is returned.
Returns
Matrix matrix A from the augmented linear matrix
get_row()
std::vector<double> Matrix::get_row (const int & y) const
Parameters
y index of the row to be returned (zero based)
Returns
y-th row of the matrix as vector of elements
get_transposition()
Matrix Matrix::get_transposition () const
Copies the matrix and transposes it. The modified copy is returned.
Returns
Matrix transposition of the matrix
index()
size_t Matrix::index (const int & x, const int & y) const
Parameters
x index of the column
y index of the row
Returns
index of element on [x,y] coords in the matrix
is_square()
bool Matrix::is_square () const
Checks if the matrix is square (size n * n).
Returns
true if matrix is square, false otherwise
operator=() [1/2]
Matrix& Matrix::operator= (const Matrix & rhs)
Copy assignment.
Parameters
rhs matrix to copy from
Returns
reference to this
operator=() [2/2]
Matrix& Matrix::operator= (Matrix && rhs) noexcept
Move assignment.
Parameters
rhs matrix to move from
Returns
reference to this
set_column()
void Matrix::set_column (const int & x, std::vector< double > values)
Sets x-th column of the matrix to be given vector of values.
Parameters
x index of the column to be set (zero based)
values vector of doubles to be inserted in the given column
set_field()
void Matrix::set_field (const int & x, const int & y, double value)
Sets value of element on [x,y] coords in the matrix.
Parameters
x index of the column in which the field is (zero based)
y index of the row in which the field is (zero based)
value double to be inserted into the matrix
Referenced by foreach_field().
set_row()
void Matrix::set_row (const int & y, std::vector< double > values)
Sets y-th row of the matrix to be given vector of values.
Parameters
y index of the row to be set (zero based)
values vector of doubles to be inserted in the given column
swap()
void Matrix::swap (Matrix & rhs)
Swaps contents of the two matrices.
Parameters
rhs
Field Documentation
augmented
bool Matrix::augmented
Definition at line 22 of file matrix.hpp.
data
double* Matrix::data {}
Definition at line 21 of file matrix.hpp.
height
int Matrix::height
Definition at line 20 of file matrix.hpp.
Referenced by foreach_field().
width
int Matrix::width
Definition at line 19 of file matrix.hpp.
Referenced by foreach_field().
The documentation for this struct was generated from the following file:
D:/CVUT/PJC/tomanm10/matrix.hpp